blank_issues_enabled: true
contact_links:
  - name: üí¨ –û–±—Å—É–∂–¥–µ–Ω–∏—è
    url: https://github.com/yellow-hammer/1c-platform-tools/discussions
    about: –ó–∞–¥–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å –∏–ª–∏ –ø–æ–¥–µ–ª–∏—Ç–µ—Å—å –∏–¥–µ—è–º–∏ –≤ –æ–±—Å—É–∂–¥–µ–Ω–∏—è—Ö
  - name: üìö –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è
    url: https://github.com/yellow-hammer/1c-platform-tools#readme
    about: –ü—Ä–æ—á–∏—Ç–∞–π—Ç–µ –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—é –ø—Ä–æ–µ–∫—Ç–∞
